calculator_ui <- function() {
  shiny::fluidPage(
    shiny::tags$head(
      shiny::tags$meta(name = "viewport", content = "width=device-width, initial-scale=1"),
      shiny::tags$link(rel = "stylesheet", href = "styles.css"),
      shiny::tags$script(src = "clipboard.js")
    ),
    title = "Sample size and power calculator",
    shiny::tags$div(class = "app-shell",
      shiny::tags$header(class = "app-header",
        shiny::tags$div(class = "brand", "RESEARCH METHODS", shiny::tags$span(" / SAMPLE SIZE")),
        shiny::tags$div(class = "version", "SAMPLE SIZE & POWER")
      ),
      shiny::tags$section(class = "intro",
        shiny::tags$p(class = "eyebrow", "ESTIMATION AND GROUP COMPARISON"),
        shiny::tags$h1("Plan your sample. Show your calculation."),
        shiny::tags$p(class = "intro-text", "Plan precision, compare independent groups, or check power. Choose a comparison objective and export the formulas, input values, and calculation steps together.")
      ),
      shiny::tags$div(class = "calculator-grid",
        shiny::tags$aside(class = "input-panel", tabindex = "0", `aria-label` = "Calculation inputs scroll area",
          shiny::tags$div(class = "panel-heading", shiny::tags$h2("Calculation inputs"),
            shiny::actionButton("reset", "Reset", class = "reset-button")),
          shiny::selectInput("calculator", "Calculator", choices = c(
            "Single proportion" = "single_proportion", "Two proportions" = "two_proportions",
            "Single mean" = "single_mean", "Two means" = "two_means",
            "Taro Yamane finite population" = "yamane"), selectize = FALSE),
          shiny::tags$div(class = "form-divider"),
          shiny::conditionalPanel("input.calculator === 'two_proportions' || input.calculator === 'two_means'",
            shiny::textInput("group1_name", "First group name", "Group 1"),
            shiny::textInput("group2_name", "Second group name", "Group 2"),
            shiny::selectInput("objective", "Comparison objective", c(
              "Equality (two-sided difference test)" = "equality", "Superiority" = "superiority",
              "Non-inferiority" = "noninferiority", "Equivalence" = "equivalence"), selectize = FALSE),
            shiny::conditionalPanel("input.objective === 'superiority' || input.objective === 'noninferiority'",
              shiny::selectInput("direction", "Direction of benefit for group 2", c("Higher outcome is better" = "higher", "Lower outcome is better" = "lower"), selectize = FALSE)),
            shiny::conditionalPanel("input.objective === 'noninferiority' && input.calculator === 'two_proportions'",
              shiny::numericInput("ni_pp", "Non-inferiority margin (percentage points)", 5, min = .001, max = 99.999, step = .5)),
            shiny::conditionalPanel("input.objective === 'noninferiority' && input.calculator === 'two_means'",
              shiny::numericInput("ni_mean", "Non-inferiority margin (outcome units)", 5, min = .001, step = .5)),
            shiny::conditionalPanel("input.objective === 'superiority' && input.calculator === 'two_proportions'",
              shiny::numericInput("superiority_pp", "Superiority margin (percentage points)", 0, min = 0, max = 99.999, step = .5)),
            shiny::conditionalPanel("input.objective === 'superiority' && input.calculator === 'two_means'",
              shiny::numericInput("superiority_mean", "Superiority margin (outcome units)", 0, min = 0, step = .5)),
            shiny::conditionalPanel("input.objective === 'superiority'",
              shiny::tags$p(class = "field-help", "Use 0 to test for any improvement, or enter a clinically justified improvement margin.")),
            shiny::conditionalPanel("input.objective === 'equivalence' && input.calculator === 'two_proportions'",
              shiny::numericInput("lower_pp", "Lower equivalence margin (percentage points)", -5, min = -99.999, max = -.001, step = .5),
              shiny::numericInput("upper_pp", "Upper equivalence margin (percentage points)", 5, min = .001, max = 99.999, step = .5)),
            shiny::conditionalPanel("input.objective === 'equivalence' && input.calculator === 'two_means'",
              shiny::numericInput("lower_mean", "Lower equivalence margin (outcome units)", -5, max = -.001, step = .5),
              shiny::numericInput("upper_mean", "Upper equivalence margin (outcome units)", 5, min = .001, step = .5)),
            shiny::conditionalPanel("input.objective === 'equivalence'",
              shiny::tags$p(class = "field-help", "Margins apply to group 2 minus group 1. For sample size, the expected difference must lie strictly inside them.")),
            shiny::conditionalPanel("input.objective === 'noninferiority'",
              shiny::tags$p(class = "field-help", "Enter a clinically justified maximum acceptable loss of benefit. Equal expected outcomes are allowed.")),
            shiny::tags$div(class = "form-divider")),
          shiny::conditionalPanel("input.calculator === 'single_proportion'",
            shiny::numericInput("p_pct", "Expected proportion (%)", 50, min = 0.001, max = 99.999, step = 1),
            shiny::tags$p(class = "field-help", "Use 50% when a suitable prior estimate is unavailable."),
            shiny::radioButtons("precision_type", "Precision", c("Absolute" = "absolute", "Relative" = "relative"), selected = "absolute", inline = TRUE),
            shiny::conditionalPanel("input.precision_type === 'absolute'",
              shiny::numericInput("absolute_pct", "Margin of error (percentage points)", 5, min = 0.001, max = 100, step = 0.5),
              shiny::tags$p(class = "field-help", "5 percentage points is an absolute margin of 0.05.")),
            shiny::conditionalPanel("input.precision_type === 'relative'",
              shiny::numericInput("relative_pct", "Relative margin of error (% of proportion)", 10, min = 0.001, max = 100, step = 1),
              shiny::tags$p(class = "field-help", "10% of a proportion of 50% gives 5 percentage points."))
          ),
          shiny::conditionalPanel("input.calculator === 'single_mean'",
            shiny::numericInput("mean_sd", "Anticipated standard deviation", 10, min = 0.001, step = 0.5),
            shiny::numericInput("mean_precision", "Absolute margin of error", 2, min = 0.001, step = 0.5),
            shiny::tags$p(class = "field-help", "Use the same measurement units for the standard deviation and margin of error.")),
          shiny::conditionalPanel("input.calculator === 'yamane'",
            shiny::numericInput("population_size", "Finite population size N", 1000, min = 1, step = 1),
            shiny::numericInput("yamane_precision_pct", "Precision (percentage points)", 5, min = .001, max = 99.999, step = .5),
            shiny::tags$p(class = "field-help", "Taro Yamane's simplified formula assumes simple random sampling, approximately 95% confidence, and a proportion of 50%. It does not use a power input.")),
          shiny::conditionalPanel("input.calculator === 'two_proportions'",
            shiny::numericInput("p1_pct", "Group 1 expected proportion (%)", 20, min = 0.001, max = 99.999, step = 1),
            shiny::selectInput("effect_type", "Specify group 2 using", c("Expected proportion" = "proportions", "Odds ratio" = "or", "Risk ratio" = "rr"), selectize = FALSE),
            shiny::conditionalPanel("input.effect_type === 'proportions'",
              shiny::numericInput("p2_pct", "Group 2 expected proportion (%)", 30, min = 0.001, max = 99.999, step = 1)),
            shiny::conditionalPanel("input.effect_type === 'or'",
              shiny::numericInput("odds_ratio", "Odds ratio (group 2 / group 1)", 1.714285714285714, min = 0.001, step = 0.1)),
            shiny::conditionalPanel("input.effect_type === 'rr'",
              shiny::numericInput("risk_ratio", "Risk ratio (group 2 / group 1)", 1.5, min = 0.001, step = 0.1)),
            shiny::tags$p(class = "field-help", "The same event must define the outcome in both groups. Ratios refer to group 2 relative to group 1.")),
          shiny::conditionalPanel("input.calculator === 'two_means'",
            shiny::numericInput("mean1", "Group 1 expected mean", 100, step = 1),
            shiny::numericInput("mean2", "Group 2 expected mean", 105, step = 1),
            shiny::selectInput("sd_method", "Standard deviation input", c(
              "Separate group SDs" = "separate", "Enter pooled SD directly" = "pooled",
              "Compute pooled SD from reference groups" = "reference"), selectize = FALSE),
            shiny::conditionalPanel("input.sd_method !== 'pooled'",
              shiny::numericInput("sd1", "Group 1 standard deviation", 15, min = 0.001, step = 0.5),
              shiny::numericInput("sd2", "Group 2 standard deviation", 15, min = 0.001, step = 0.5)),
            shiny::conditionalPanel("input.sd_method === 'pooled'",
              shiny::numericInput("pooled_sd", "Reported pooled standard deviation", 15, min = .001, step = .5)),
            shiny::conditionalPanel("input.sd_method === 'reference'",
              shiny::numericInput("ref_n1", "Reference study group 1 sample size", 50, min = 2, step = 1),
              shiny::numericInput("ref_n2", "Reference study group 2 sample size", 100, min = 2, step = 1),
              shiny::tags$p(class = "field-help", "Enter the reference study's SDs above. Its sample sizes weight the within-group pooled variance; they are separate from your planned group sizes.")),
            shiny::tags$p(class = "field-help", "Use the same outcome units throughout. Pooled SD assumes a common within-group variance; separate SDs allow different variances.")),
          shiny::conditionalPanel("input.calculator === 'single_proportion' || input.calculator === 'single_mean'",
            shiny::tags$div(class = "form-divider"),
            shiny::radioButtons("confidence_mode", "Critical value", c("Confidence level" = "confidence", "Custom Z" = "z"), selected = "confidence", inline = TRUE),
            shiny::conditionalPanel("input.confidence_mode === 'confidence'",
              shiny::numericInput("confidence_pct", "Two-sided confidence level (%)", 95, min = 0.001, max = 99.999, step = 1)),
            shiny::conditionalPanel("input.confidence_mode === 'z'",
              shiny::numericInput("z", "Standard-normal critical value Z", 1.96, min = 0.001, step = 0.01),
              shiny::tags$p(class = "field-help", "The supplied Z is used directly; implied confidence is reported."))),
          shiny::conditionalPanel("input.calculator === 'two_proportions' || input.calculator === 'two_means'",
            shiny::tags$div(class = "form-divider"),
            shiny::radioButtons("comparison_mode", "Solve for", c("Sample size" = "sample_size", "Power" = "power"), selected = "sample_size", inline = TRUE),
            shiny::numericInput("alpha_pct", "Significance level alpha (%)", 5, min = 0.001, max = 99.999, step = .5),
            shiny::uiOutput("comparison_help"),
            shiny::conditionalPanel("input.comparison_mode === 'sample_size'",
              shiny::numericInput("power_pct", "Target power (%)", 80, min = 50.001, max = 99.999, step = 1),
              shiny::numericInput("allocation_ratio", "Group size ratio (group 2 / group 1)", 1, min = 0.001, step = 0.5),
              shiny::tags$p(class = "field-help", "1 gives equal groups. 2 plans twice as many complete observations in group 2. Target power must exceed 50%.")),
            shiny::conditionalPanel("input.comparison_mode === 'power'",
              shiny::numericInput("fixed_n1", "Group 1 complete sample size", 100, min = 2, step = 1),
              shiny::numericInput("fixed_n2", "Group 2 complete sample size", 100, min = 2, step = 1),
              shiny::tags$p(class = "field-help", "Enter whole-number analysable group sizes. Power uses the selected comparison hypothesis.")),
            shiny::tags$p(class = "method-note", "Two independent groups · Normal approximation")),
          shiny::conditionalPanel("(input.calculator !== 'two_proportions' && input.calculator !== 'two_means') || input.comparison_mode === 'sample_size'",
            shiny::numericInput("nonresponse_pct", "Expected non-response (%)", 10, min = 0, max = 99.999, step = 1),
            shiny::tags$p(class = "field-help", "Enter 0 for no adjustment. For comparisons, this applies to each group.")),
          shiny::tags$div(class = "input-note", "Results update as you change the inputs.")
        ),
        shiny::tags$main(class = "results-panel", tabindex = "0", `aria-label` = "Calculation results scroll area",
          shiny::uiOutput("result_summary"), shiny::uiOutput("export_actions"),
          shiny::tags$section(class = "report-panel",
            shiny::tabsetPanel(id = "report_tab", type = "tabs",
              shiny::tabPanel("Calculation report", value = "report", shiny::uiOutput("report_preview")),
              shiny::tabPanel("Markdown", value = "markdown",
                shiny::tags$div(class = "markdown-toolbar",
                  shiny::tags$p("Includes LaTeX equations for Quarto and R Markdown."),
                  shiny::tags$button(id = "copy_markdown", type = "button", class = "copy-button", "Copy as Markdown")),
                shiny::uiOutput("markdown_source"),
                shiny::tags$p(id = "copy_status", role = "status", `aria-live` = "polite"))))
        )
      ),
      shiny::tags$footer(class = "app-footer",
        shiny::tags$span("Independent observations · Transparent formulas · Reproducible reports"),
        shiny::tags$span("Developed by Dr Naveen Suthar"))
    )
  )
}
